import { Component } from '@angular/core';
import { RolePermissions } from '../../../../interfaces/roles.interfaces';

@Component({
    templateUrl: './names-permisos.component.html',
    styles: ``,
    standalone: false
})
export class NamesPermisosComponent {
    public permisoNombres: { [key: string]: string } = {
      list_roles: 'Listar Roles',
      add_roles: 'Agregar Roles',
      modify_roles: 'Modificar Roles',
      delete_roles: 'Eliminar Roles',
      list_users: 'Listar Usuarios',
      add_users: 'Agregar Usuarios',
      modify_users: 'Modificar Usuarios',
      delete_users: 'Eliminar Usuarios',
      list_unit_org: 'Listar Unidades Organizativas',
      list_sales_org: 'Listar Organizaciones de Ventas',
      add_sales_org: 'Agregar Organizaciones de Ventas',
      modify_sales_org: 'Modificar Organizaciones de Ventas',
      delete_sales_org: 'Eliminar Organizaciones de Ventas',
      list_devices: 'Listar Dispositivos',
      add_devices: 'Agregar Dispositivos',
      modify_devices: 'Modificar Dispositivos',
      delete_devices: 'Eliminar Dispositivos',
      list_accounts: 'Listar Cuentas',
      add_accounts: 'Agregar Cuentas',
      modify_accounts: 'Modificar Cuentas',
      delete_accounts: 'Eliminar Cuentas',
      list_prospects: 'Listar Prospectos',
      add_prospects: 'Agregar Prospectos',
      modify_prospects: 'Modificar Prospectos',
      list_type_accounts: 'Listar Tipos de Cuentas',
      add_type_accounts: 'Agregar Tipos de Cuentas',
      modify_type_accounts: 'Modificar Tipos de Cuentas',
      delete_type_accounts: 'Eliminar Tipos de Cuentas',
      list_classifications_accounts: 'Listar Clasificaciones de Cuentas',
      add_classifications_accounts: 'Agregar Clasificaciones de Cuentas',
      modify_classifications_accounts: 'Modificar Clasificaciones de Cuentas',
      delete_classifications_accounts: 'Eliminar Clasificaciones de Cuentas',
      lista_contacts: 'Listar Contactos',
      add_contacts: 'Agregar Contactos',
      modify_contacts: 'Modificar Contactos',
      delete_contacts: 'Eliminar Contactos',
      list_warehouses: 'Listar Almacenes',
      add_warehouses: 'Agregar Almacenes',
      modify_warehouses: 'Modificar Almacenes',
      delete_warehouses: 'Eliminar Almacenes',
      list_routes: 'Listar Rutas',
      add_routes: 'Agregar Rutas',
      modify_routes: 'Modificar Rutas',
      delete_routes: 'Eliminar Rutas',
      list_trucks: 'Listar Camiones',
      add_trucks: 'Agregar Camiones',
      modify_trucks: 'Modificar Camiones',
      delete_trucks: 'Eliminar Camiones',
      list_payment_conditions: 'Listar Condiciones de Pago',
      add_payment_conditions: 'Agregar Condiciones de Pago',
      modify_payment_conditions: 'Modificar Condiciones de Pago',
      delete_payment_conditions: 'Eliminar Condiciones de Pago', 
      list_competence_business:'Listar Competencias Empresariales', 
      add_competence_business:'Agregar Competencias Empresariales', 
      modify_competence_business:'Modificar Competencias Empresariales', 
      delete_competence_business:'Eliminar Competencias Empresariales', 
      list_competence_products:'Listar Competencias de Productos', 
      add_competence_products:'Agregar Competencias de Productos', 
      modify_competence_products:'Modificar Competencias de Productos', 
      delete_competence_products:'Eliminar Competencias de Productos', 
      list_order_type:'Listar Tipos de Orden', 
      add_order_type:'Agregar Tipos de Orden', 
      modify_order_type:'Modificar Tipos de Orden', 
      delete_order_type:'Eliminar Tipos de Orden', 
      list_group_promotions:'Listar Promociones por Grupo', 
      add_group_promotions:'Agregar Promociones por Grupo', 
      modify_group_promotions:'Modificar Promociones por Grupo', 
      delete_group_promotions:'Eliminar Promociones por Grupo', 
      list_promotions:'Listar Promociones', 
      add_promotions:'Agregar Promociones', 
      modify_promotions:'Modificar Promociones', 
      delete_promotions:'Eliminar Promociones', 
      list_orders:'Listar Órdenes', 
      add_orders:'Agregar Órdenes', 
      modify_orders:'Modificar Órdenes', 
      delete_orders:'Eliminar Órdenes', 
      list_collections:'Listar Colecciones', 
      add_collections:'Agregar Colecciones', 
      modify_collections:'Modificar Colecciones', 
      delete_collections:'Eliminar Colecciones', 
      list_collections_pending:'Listar Colecciones Pendientes', 
      add_collections_pending:'Agregar Colecciones Pendientes', 
      modify_collections_pending:'Modificar Colecciones Pendientes', 
      delete_collections_pending:'Eliminar Colecciones Pendientes', 
      list_returns:'Listar Devoluciones', 
      add_returns:'Agregar Devoluciones', 
      modify_returns:'Modificar Devoluciones', 
      delete_returns:'Eliminar Devoluciones', 
      list_credit_note:'Listar Notas de Crédito', 
      add_credit_note:'Agregar Notas de Crédito', 
      modify_credit_note:'Modificar Notas de Crédito', 
      delete_credit_note:'Eliminar Notas de Crédito', 
      list_debit_note:'Listar Notas de Débito', 
      add_debit_note:'Agregar Notas de Débito', 
      modify_debit_note:'Modificar Notas de Débito', 
      delete_debit_note:'Eliminar Notas de Débito'
    };



}
